name: elementexplorer
version: "0.1.1"
summary: CLI Tool
description: |
  A CLI tool for element details.

grade: stable
base: core22
confinement: strict

apps:
  elementexplorer:
    command: bin/elementexplorer

parts:
  elementexplorer:
    source: .
    plugin: dump
    organize:
      "elementexplorer": "/usr/local/bin/elementexplorer"
